config/routes.rb
Rails.application.routes.draw do

  resources :beers
  resources :brewers
  resources :comments
  resources :blog_posts
root 'home#index'
get 'user/show'

devise_for :users

resources :users, only: [:show]

end

app/models/brewer.rb
class Brewer < ActiveRecord::Base
	has_many :beers
	belongs_to :user
end

app/controllers/brewers_controller.rb
class BrewersController < ApplicationController
  before_action :set_brewer, only: [:show, :edit, :update, :destroy]

  # GET /brewers
  # GET /brewers.json
  def index
    @brewers = Brewer.all
  end

  # GET /brewers/1
  # GET /brewers/1.json
  def show
  end

  # GET /brewers/new
  def new
    @brewer = Brewer.new
  end

  # GET /brewers/1/edit
  def edit
  end

  # POST /brewers
  # POST /brewers.json
  def create
    @brewer = Brewer.new(brewer_params)

    respond_to do |format|
      if @brewer.save
        format.html { redirect_to @brewer, notice: 'Brewer was successfully created.' }
        format.json { render :show, status: :created, location: @brewer }
      else
        format.html { render :new }
        format.json { render json: @brewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brewers/1
  # PATCH/PUT /brewers/1.json
  def update
    respond_to do |format|
      if @brewer.update(brewer_params)
        format.html { redirect_to @brewer, notice: 'Brewer was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewer }
      else
        format.html { render :edit }
        format.json { render json: @brewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brewers/1
  # DELETE /brewers/1.json
  def destroy
    @brewer.destroy
    respond_to do |format|
      format.html { redirect_to brewers_url, notice: 'Brewer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewer
      @brewer = Brewer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewer_params
      params.require(:brewer).permit(:location, :phnumber, :website, :rating, :name, :review, :user_id, :phone_number)
    end
end

app/helpers/brewers_helper.rb
module BrewersHelper
end

app/views/brewers/_form.html.erb
<%= simple_form_for(@brewer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name , :input_html => {:style=> 'width: 40%'} %>
    <%= f.input :rating , :input_html => {:style=> 'width: 40%'}%>
    <%= f.input :location, :input_html => {:style=> 'width: 40%'} %>
    <%= f.input :phone_number, :input_html => {:style=> 'width: 40%'} %>
    <%= f.input :website, :input_html => {:style=> 'width: 40%'} %>
    <%= f.input :review, :input_html => {:style=> 'width: 40%'} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/brewers/edit.html.erb
<h1>Editing Brewer</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewer %> |
<%= link_to 'Back', brewers_path %>

app/views/brewers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Brewers</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Phone Number</th>
      <th>Website</th>
      <th>Rating</th>
      <th>Name</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brewers.each do |brewer| %>
      <tr>
        <td><%= brewer.location %></td>
        <td><%= brewer.phone_number %></td>
        <td><%= brewer.website %></td>
        <td><%= brewer.rating %></td>
        <td><%= brewer.name %></td>
        <td><%= brewer.review %></td>
        <td><%= link_to 'Show', brewer %></td>
        <td><%= link_to 'Edit', edit_brewer_path(brewer) %></td>
        <td><%= link_to 'Destroy', brewer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brewer', new_brewer_path %>

app/views/brewers/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', brewers_path %>

app/views/brewers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @brewer.location %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @brewer.phone_number %>
</p>

<p>
  <strong>Website:</strong>
  <%= @brewer.website %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @brewer.rating %>
</p>

<p>
  <strong>Name:</strong>
  <%= @brewer.name %>
</p>

<p>
  <strong>Review:</strong>
  <%= @brewer.review %>
</p>

<%= link_to 'Edit', edit_brewer_path(@brewer) %> |
<%= link_to 'Back', brewers_path %>