config/routes.rb
Rails.application.routes.draw do

  resources :beers
  resources :brewers
  resources :comments
  resources :blog_posts
root 'home#index'
get 'user/show'

devise_for :users

resources :users, only: [:show]

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(image_tag("OnTap_logo.png", :alt => "logo", :title => "Home"), root_path) %>
    </div>

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"></li>
        <li></li>
        <li class="dropdown">
          
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          
        </div>
        
      </form>
      <% if current_user %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Find a Brewery', brewers_path %></li>
            <li><%= link_to 'Find a Beer', beers_path %></li>
            <li><%= link_to 'Brew News', blog_posts_path %></li>
            <li><%= link_to 'Write a Review', new_brewer_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            
          <% else %>
           
           <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Home', root_path %></li>
              <li><%= link_to 'Find a Brewery', brewers_path %></li>
              <li><%= link_to 'Find a Beer', beers_path %></li>
              <li><%= link_to 'Brew News', blog_posts_path %></li>
              <li><%= link_to 'Write a Review', new_brewer_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <li><%= link_to 'Login', new_user_session_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ontap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<nav><%= render 'layouts/navbar' %></nav>
<body>

<%= yield %>

</body>
</html>